### ISSUE TITLE
Regenerate API token

### ISSUE THREAD

**Issue by piazzaana** [piazzaana/chicken-fries#58]
make this an Environmental Variable and regenerate a new token 

Note from Chapman:
> public/javascripts/checkout.js: `const stripe = Stripe('pk_test_rmALB2lGQQER0zyeD1O6wsAu');
 `

**Comment by piazzaana** [comment]
@reactivepixel Hi Chris, I tried to set the token as a env var, but the code is breaking, I might need some help with this one, the old is no longer working though.

**Comment by reactivepixel** [comment]
@piazzaana Are your env vars not showing up? That's going to be the key. Making certain that your .env file has the correct information and the file that you are trying to use that information is actually loading in the Env's
