### ISSUE TITLE
Add root readme with setup details

### ISSUE THREAD

**Issue by markmichon** [piazzaana/chicken-fries#8]
In addition to the spec in the docs folder, the root of your repo also needs a `readme.md` file explaining how to set up an run the project. Things like: installing dependencies, running mongo, running the app, etc.

**Comment by piazzaana** [comment]
@markmichon Ok, I think I might have deleted it in order to fix the conflicts, I'll fix it ASAP. 
Thanks

**Comment by piazzaana** [comment]
@markmichon  I've just checked, it is there, I renamed it to installation because of the conflicts

**Comment by markmichon** [comment]
Ah, I see it. In your next round of additions swap it over to readme and update it with any necessary details (like database) that come up in the current milestone.

**Comment by piazzaana** [comment]
Will do. Thanks
